// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 3/22/2025, 4:19:51 PM
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/project/sandbox/user-workspace/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/project/sandbox/user-workspace/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/project/sandbox/user-workspace/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/project/sandbox/user-workspace/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/project/sandbox/user-workspace/plugins/**/*.{js,ts,mjs}","/project/sandbox/user-workspace/composables/**/*.{js,ts,mjs}","/project/sandbox/user-workspace/utils/**/*.{js,ts,mjs}","/project/sandbox/user-workspace/pages/index.vue","/project/sandbox/user-workspace/pages/forms/form-layouts.vue","/project/sandbox/user-workspace/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/project/sandbox/user-workspace/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/project/sandbox/user-workspace/app.config.{js,ts,mjs}"]}},
{"content":[],"theme":{"extend":{"colors":{"primary":{"50":"#f0f9ff","100":"#e0f2fe","200":"#bae6fd","300":"#7dd3fc","400":"#38bdf8","500":"#0ea5e9","600":"#0284c7","700":"#0369a1","800":"#075985","900":"#0c4a6e"}}}}},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;